name: 'PR Labeler'
description: 'Automatically labels your PRs based on branch name patterns like feature/* or fix/*.'
author: 'Timon van Spronsen'
inputs:
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/pr-labeler.yml'
  require-labeling:
    description: 'true means at least 1 labeling rule needs to be matched'
    default: 'false'
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: 'node12'
  main: 'index.js'
