name: 'PR Labeler'
description: 'Automatically labels your PRs based on branch name patterns like feature/* or fix/*.'
author: 'Timon van Spronsen'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`'
    default: ${{ github.token }}
  configuration-path:
    description: 'Path to label configurations'
    default: '.github/pr-labeler.yml'
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: 'node20'
  main: 'dist/index.js'
