name: 'PR Labeler'
description: 'Automatically labels your PRs based on branch name patterns like feature/* or fix/*.'
author: 'Timon van Spronsen'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`'
    default: ${{ github.token }}
  configuration-path:
    description: 'Path to label configurations'
    default: '.github/pr-labeler.yml'
  default-label:
    description: 'If the branch name does not match the label configuration, use this tag'
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: 'node16'
  main: 'index.js'
